kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: local
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: zk-pv-volume-0
  labels:
    type: local
spec:
  storageClassName: local
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/pv/zk/zk-0"
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: zk-pv-volume-1
  labels:
    type: local
spec:
  storageClassName: local
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/pv/zk/zk-1"
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: zk-pv-volume-2
  labels:
    type: local
spec:
  storageClassName: local
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/pv/zk/zk-2"
